server:
  port: 8091
spring:
  dubbo:
    application:
      name: dubbo-provider # 应用名
    registry:
      address: zookeeper://localhost #zookeeper地址
      port: 2181
    protocol:
      name: dubbo
      port: 10001  #dubbo服务暴露的端口
    scan: com.kingfish.dubboproviderdemo.service # 扫描的包路径
